config/routes.rb
Rails.application.routes.draw do

  resources :subjects do
    member do
      get :delete
    end
  end

  # simple route
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'

  # root route, where the homepage go
  root 'demo#hello'

  # default route
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :subject
  has_many :sections
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :page
end

app/models/subject.rb
class Subject < ApplicationRecord

  #has_one :page
  has_many :pages

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, -> { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }

  # def sef.search(query)
  #   where(["name LIKE ?", "%#{query}%"])
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # If you changed the table user to admin_user, then either rename this rb file to AdminUsers
  # or self.table_name="admin_users"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  # call the index action, and render the demo/index template
  def index
    @number_array=[1,2,3]
    render('index')
  end

  def hello
    @id=params[:id]
    @page=params['page']
    render('hello')
  end

  def other_hello
    redirect_to(:controller => 'demo', :action => 'index')
  end

  def lynda
    redirect_to('http://www.lynda.com')
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects=Subject.all
  end

  def show
    @subject=Subject.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/hello.html.erb
<h1>Hello Hello</h1>

ID: <%= @id %> <br/>
Page : <%= @page %> <br/>
Next page : <%= @page.to_i + 1 %>

app/views/demo/index.html.erb
  <h1>Hello Index</h1>
  <%= 1+1 %>
  <%target="Target"%>
  <br/>
  <%="This is a #{target}"%>
  <br/>
  <% 3.times do |n| %>
   <%=n %><br/>
  <% end %>
  <br/>
  <% @number_array.each do |n| %>
   <%=n %><br/>
  <% end %>

  <%= link_to('The hello page', {:action => 'hello'}) %> <br/>
  <%= link_to('The hello page with params', {:action => 'hello', :page => '5', :id => 1}) %> <br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

app/views/subjects/index.html.erb
<h1>Subjects</h1>
<%= link_to("Add new subject", new_subject_path, :class => 'action new') %>
<table class="listing" summary="Subject list">
  <tr class="header">
    <th>#</th>
    <th>Subject</th>
    <th>Visible</th>
    <th>Pages</th>
    <th>Actions</th>
  </tr>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
  <% end %>
</table>

app/views/subjects/new.html.erb
<h1>Subjects#new</h1>
<p>Find me in app/views/subjects/new.html.erb</p>

app/views/subjects/show.html.erb
<h1>Subject</h1>
<p> <%= @subject.name %> </p>